IDENTIFIERS = {
    "txt": "text, plain-text, document, notes",
    "h": "text, code, header, c, c++, programming",
    "html": "text, markup, web, html",
    "png": "binary, image, bitmap, png",
    "py": "text, code, python, automation",
    "js": "text, code, javascript, web, front-end, back-end",
    "pyc": "binary, python, compiled",
    "gz": "binary, compressed, archive, gzip",
    "go": "text, code, go",
    "rb": "text, code, ruby",
    "json": "text, data, json, serialization",
    "dat": "binary, data, generic",
    "xnb": "binary, game, xna",
    "hpp": "text, code, header, c++",
    "asm": "text, code, assembly",
    "rs": "text, code, rust",
    "zst": "binary, compressed, archive zstd",
    "xz": "binary, compressed, archive, xz",
    "md": "text, markup, markdown, documentation",
    "ri": "text, code, ruby, rdoc, documentation",
    "xml": "text, markup, xml, data, configuration",
    "so": "binary, linux, library",
    "pyi": "text, code, python, stub, typing",
    "code": "text, code, vscode, editor, settings",
    "dll": "binary, dll, windows, library",
    "c": "text, code, c",
    "vim": "text, code, vim, editor, settings",
    "cmake": "text, code, cmake, build, configuration",
    "a": "binary, archive, library",
    "rst": "text, markup, documentation",
    "pl": "text, code, perl, scripting",
    "toml": "text, configuration, toml",
    "ttf": "binary, font, ttf",
    "qm": "binary, qt, message, localization",
    "jar": "binary, java, archive, jar",
    "mod": "binary, game, minecraft, mod",
    "docbook": "text, markup, documentation, docbook",
    "qml": "text, markup, qt, qml",
    "bin": "binary, executable, binary data",
    "lua": "text, code, lua, scripting",
    "jpg": "binary, image, jpeg",
    "sample": "text, example, sample",
    "0": "binary, data, empty",
    "yml": "text, configuration, yaml",
    "inc": "text, code, header, include",
    "sig": "binary, signature, gpg, pgp",
    "ts": "text, code, typescript",
    "jl": "text, code, julia",
    "css": "text, stylesheet, css",
    "conf": "text, configuration, generic",
    "pc": "text, code, pascal, compile",
    "sh": "text, code, shell, scripting",
    "pm": "text, code, perl, module",
    "bz2": "binary, compressed, bzip2",
    "desktop": "text, markup, desktop, configuration",
    "java": "text, code, java",
    "zip": "binary, compressed, archive, zip",
    "bntl": "binary, game, unity, assetbundle",
    "page": "text, markup, html, web",
    "s": "text, code, assembly, linker",
    "ui": "text, markup, qt, ui",
    "cpp": "text, code, c++, programming",
    "cl": "text, code, opencl, gpu",
    "php": "text, code, php, scripting",
    "md5": "text, hash, md5",
    "qmlc": "binary, qt, qml, compiled",
    "tgz": "binary, compressed, archive, tar, gzip",
    "symbols": "binary, symbols, debugging",
    "pak": "binary, game, unreal, pak",
    "sip": "text, code, python, sip, bindings",
}
