IDENTIFIERS = {
    "txt": "text, plain-text, document, notes",
    "h": "text, code, header, c, c++",
    "html": "text, markup, web, html",
    "png": "binary, image, bitmap, png",
    "py": "text, code, python, automation",
    "js": "text, code, javascript, web, front-end, back-end",
    "pyc": "binary, python, compiled",
    "gz": "binary, compressed, archive, gzip",
    "go": "text, code, go",
    "rb": "text, code, ruby",
    "json": "text, data, json, serialization",
    "dat": "binary, data, generic",
    "xnb": "binary, game, xna",
    "hpp": "text, code, header, c++",
    "asm": "text, code, assembly",
    "rs": "text, code, rust",
    "zst": "binary, compressed, archive zstd",
    "xz": "binary, compressed, archive, xz",
    "md": "text, markup, markdown, documentation",
    "ri": "text, code, ruby, rdoc, documentation",
    "xml": "text, markup, xml, data, configuration",
    "so": "binary, linux, library",
    "pyi": "text, code, python, stub, typing",
    "code": "text, code, vscode, editor, settings",
    "dll": "binary, dll, windows, library",
    "c": "text, code, c",
    "vim": "text, code, vim, editor, settings",
    "cmake": "text, code, cmake, build, configuration",
    "a": "binary, archive, library",
    "rst": "text, markup, documentation",
    "pl": "text, code, perl",
    "toml": "text, configuration, toml",
    "ttf": "binary, font, ttf",
    "qm": "binary, qt, message, localization",
    "jar": "binary, java, archive, jar",
    "mod": "binary, game, minecraft, mod",
    "docbook": "text, markup, documentation, docbook",
    "qml": "text, markup, qt, qml",
    "bin": "binary, executable, binary data",
    "lua": "text, code, lua",
    "jpg": "binary, image, jpeg",
    "sample": "text, example, sample",
    "0": "binary, data, empty",
    "yml": "text, configuration, yaml",
    "inc": "text, code, header, include",
    "sig": "binary, signature, gpg, pgp",
    "ts": "text, code, typescript",
    "jl": "text, code, julia",
    "css": "text, stylesheet, css",
    "conf": "text, configuration, generic",
    "pc": "text, code, pascal, compile",
    "sh": "text, code, shell",
    "pm": "text, code, perl, module",
    "bz2": "binary, compressed, bzip2",
    "desktop": "text, markup, desktop, configuration",
    "java": "text, code, java",
    "zip": "binary, compressed, archive, zip",
    "bntl": "binary, game, unity, assetbundle",
    "page": "text, markup, html, web",
    "s": "text, code, assembly, linker",
    "ui": "text, markup, qt, ui",
    "cpp": "text, code, c++",
    "cl": "text, code, opencl, gpu",
    "php": "text, code, php",
    "md5": "text, hash, md5",
    "qmlc": "binary, qt, qml, compiled",
    "tgz": "binary, compressed, archive, tar, gzip",
    "symbols": "binary, symbols, debugging",
    "pak": "binary, game, unreal, pak",
    "sip": "text, code, python, sip, bindings",
    "svg": "text, markup, image, vector, svg",
    "mo": "binary, gettext, message, localization",
    "gif": "binary, image, animated, gif",
    "map": "text, data, mapping, geojson, source-map",
    "xsl": "text, markup, xslt, xml, transformation",
    "scm": "text, code, scheme",
    "tga": "binary, image, targa",
    "class": "binary, java, bytecode",
    "webp": "binary, image, webp",
    "webidl": "text, code, web, interface, idl",
    "sha1": "text, hash, sha1",
    "zsh": "text, code, shell, zsh",
    "nbt": "binary, data, minecraft, nbt",
    "exe": "binary, executable, windows",
    "nse": "text, code, nmap, engine",
    "1": "binary, data, generic",
    "cs": "text, code, csharp, dotnet",
    "pom": "text, xml, maven, build, configuration",
    "log": "text, log, data, plain-text",
    "repositories": "text, configuration, repositories",
    "orig": "binary, data, original",
    "crate": "binary, rust, package, crate",
    "tex": "text, markup, latex, typesetting",
    "snippets": "text, code, snippets, configuration",
    "lang": "text, code, language, localization",
    "service": "text, configuration, systemd, service",
    "pxd": "text, code, cython, c, declarations",
    "asset": "binary, data, game, unity",
    "in": "text, configuration, template",
    "pde": "text, code, processing, java",
    "gemspec": "text, code, ruby, gem, specification",
    "tablet": "binary, data, tablet",
    "woff2": "binary, font, web, woff2",
    "prf": "text, configuration, profile",
    "ipp": "text, code, header, c++, inline",
    "lock": "text, configuration, dependency, lock",
    "file": "binary, data, generic",
    "rc": "text, code, resource, script, windows",
    "svgz": "binary, compressed, image, vector, svg",
    "dict": "text, data, dictionary",
    "idl": "text, code, interface, definition, language",
    "2": "binary, data, generic",
    "cocci": "text, code, coccinelle, semantic, patch",
    "yaml": "text, configuration, yaml",
    "pem": "text, certificate, encryption, public, key",
    "res": "binary, resource, data, windows",
    "pri": "text, configuration, qmake, build",
    "proto": "text, code, protobuf, schema, definition",
    "jmod": "binary, java, module, jmod",
    "o": "binary, object, code, compiled",
    "meta": "text, metadata",
    "info": "text, metadata",
    "smali": "text, code, android, dex, bytecode",
    "uasset": "binary, data, unreal, asset",
    "obj": "binary, 3d, object, mesh, model",
    "dcp": "binary, cinema, package, digital",
    "mp3": "binary, audio, mp3, music",
    "precompiled": "binary, compiled, headers",
    "lcp": "binary, readium, drm, license",
    "flat": "binary, database, single, file",
    "mp4": "binary, video, mp4, m4v",
    "pdb": "binary, debug, symbols",
    "mat": "binary, material, 3d",
    "lib": "binary, library, generic",
    "wav": "binary, audio, wav",
    "dex": "binary, android, dex, bytecode",
    "ini": "text, configuration, ini",
    "mca": "binary, minecraft, level, map",
    "resources": "binary, data, generic",
    "torrent": "binary, bittorrent, torrent",
    "prefab": "binary, unity, prefab",
    "xaml": "text, markup, xaml, xml",
    "uss": "text, stylesheet, unity, uss",
    "epr": "binary, java, epr",
    "srt": "text, subtitles, srt",
    "resx": "text, .net, resource, resx",
    "psd": "binary, image, photoshop",
    "peff": "binary, image, photoshop, extensions",
    "asmdef": "text, unity, assembly, definition",
    "hlsl": "text, shader, hlsl",
    "shader": "text, shader, glsl",
    "properties": "text, configuration, properties",
    "uxml": "text, markup, unity, uxml",
    "xmp": "binary, metadata, xmp",
    "snippet": "text, code, snippet",
    "pyd": "binary, python, library, dll",
    "fbx": "binary, 3d, fbx, model",
    "udn": "text, license, unity",
    "timestamp": "text, metadata, timestamp",
    "webm": "binary, video, webm",
    "aex": "text, configuration, adobe, extension",
    "d": "text, documentation",
    "palette": "text, data, palette, colors",
    "cache": "binary, data, cache",
    "ico": "binary, icon, ico",
    "unity": "binary, data, unity, package",
    "tif": "binary, image, tiff",
    "mtl": "text, 3d, material",
    "rmeta": "text, metadata, unity, resource",
    "layout": "text, markup, layout",
}
